#ifndef _VPLS_H
#define _VPLS_H

#define	VPLS_F_INET	0x01
#define	VPLS_F_INET6	0x02
#define	VPLS_F_VLAN	0x04

enum {
	VPLS_ATTR_UNSPEC = 0,
	VPLS_ATTR_IFINDEX,
	VPLS_ATTR_WIREID,
	VPLS_ATTR_LABEL_IN,
	VPLS_ATTR_LABEL_OUT,
	VPLS_ATTR_NH_DEV,
	VPLS_ATTR_NH_IP,
	VPLS_ATTR_NH_IPV6,
	VPLS_ATTR_TTL,
	VPLS_ATTR_VLANID,
	__VPLS_ATTR_MAX,
};
#define VPLS_ATTR_MAX (__VPLS_ATTR_MAX - 1)

enum {
	VPLS_CMD_UNSPEC = 0,

	VPLS_CMD_NEWWIRE = 4,
	VPLS_CMD_DELWIRE,
	VPLS_CMD_GETWIRE,
	VPLS_CMD_SETWIRE,
	__VPLS_CMD_MAX,
};
#define VPLS_CMD_MAX (__VPLS_CMD_MAX - 1)

#endif /* _VPLS_H */
